import discord
import random

class Motivation:

    @staticmethod
    def get_motivation_embed(interaction: discord.Interaction):
        member = interaction.guild.get_member(interaction.user.id)
        username = member.nick if member.nick is not None else member.name
        messages = [
            f"You got this, **{username}**!",
            f"Believe in yourself, **{username}**!",
            f"Keep pushing forward, **{username}**!",
            f"Stay strong, **{username}**!",
            f"You're capable of great things, **{username}**!",
            f"Don't give up, **{username}**!",
            f"Take it one step at a time, **{username}**!",
            f"You're making progress, **{username}**!",
            f"Stay focused and determined, **{username}**!",
            f"Success is within reach, **{username}**!",
            f"Never stop trying, **{username}**!",
            f"Keep your head up, **{username}**!",
            f"Stay positive and keep moving forward, **{username}**!",
            f"You're on the path to greatness, **{username}**!",
            f"You have what it takes to succeed, **{username}**!",
            f"Believe in yourself and your abilities, **{username}**!",
            f"Stay motivated and keep working hard, **{username}**!",
            f"Your hard work will pay off, **{username}**!",
            f"Never give up on your dreams, **{username}**!",
            f"Stay committed and you will achieve your goals, **{username}**!",
            f"Your perseverance will lead to success, **{username}**!",
            f"Stay driven and determined, **{username}**!",
            f"You're an inspiration, **{username}**!",
            f"Keep pushing through the challenges, **{username}**!",
            f"Success is a journey, not a destination, **{username}**!",
            f"Your dedication is admirable, **{username}**!",
            f"Stay motivated and you will overcome any obstacle, **{username}**!",
            f"Stay positive and keep moving forward, **{username}**!",
            f"Believe in yourself and you can achieve anything, **{username}**!",
            f"You're capable of achieving greatness, **{username}**!",
            f"Keep chasing your dreams, **{username}**!",
            f"You have the strength and determination to succeed, **{username}**!",
            f"Stay focused on your goals, **{username}**!",
            f"Your hard work and determination will pay off, **{username}**!",
            f"Stay persistent and you will achieve your goals, **{username}**!",
            f"You're a shining example of determination, **{username}**!",
            f"Stay motivated and you will achieve your dreams, **{username}**!",
            f"Believe in yourself and your potential, **{username}**!",
            f"Your determination and hard work are inspiring, **{username}**!",
            f"Stay positive and you will attract success, **{username}**!",
            f"Your commitment to your goals is commendable, **{username}**!",
            f"Stay motivated and you will achieve great things, **{username}**!",
            f"You have the power to create your own success, **{username}**!",
            f"Believe in yourself and your abilities, and you will achieve your dreams, **{username}**!",
            f"Your perseverance and resilience are admirable, **{username}**!",
            f"Stay focused and determined, and you will achieve your goals, **{username}**!",
            f"Your hard work and dedication are paying off, **{username}**!",
            f"Stay motivated and you will reach your full potential, **{username}**!",
            f"You're an unstoppable force, **{username}**!",
            f"Keep pushing past your limits, **{username}**!",
            f"Stay positive and you will achieve greatness, **{username}**!",
            f"Believe in yourself and all that {username} is. Know that there is something inside {username} that is greater than any obstacle.",
            f"Don't watch the clock; do what it does. Keep going, {username}.",
            f"You can't go back and change the beginning, but {username} can start where {username} is and change the ending.",
            f"Believe {username} can and {username}'re halfway there.",
            f"The secret of getting ahead is getting started, {username}.",
            f"You are never too old to set another goal or to dream a new dream, {username}.",
            f"I can't change the direction of the wind, but I can adjust my sails to always reach my destination, {username}.",
            f"It does not matter how slowly {username} go as long as {username} do not stop.",
            f"Start where {username} are. Use what {username} have. Do what {username} can.",
            f"Believe in {username} and {username} will be unstoppable.",
            f"If {username} can dream it, {username} can achieve it.",
            f"The only way to do great work is to love what {username} do, {username}.",
            f"Don't let yesterday take up too much of today, {username}.",
            f"Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down, {username}.",
            f"{username} is not a product of circumstances; {username} is a product of decisions.",
            f"Believe in yourself, {username}, and all that {username} are. Know that there is something inside {username} that is greater than any obstacle.",
            f"The best way to predict {username}'s future is to create it.",
            f"Don't be pushed around by the fears in {username}'s mind. Be led by the dreams in {username}'s heart.",
            f"Believe {username} can and {username} is halfway there.",
            f"The way to get started is to quit talking and begin doing, {username}.",
            f"Believe in {username}. Have faith in {username}'s abilities. Without a humble but reasonable confidence in {username} own powers {username} cannot be successful or happy.",
            f"The only limit to {username}'s realization of tomorrow will be {username}'s doubts of today.",
            f"Don't let yesterday take up too much of today, {username}.",
            f"The only way to do great work is to love what {username} do, {username}.",
            f"Believe in {username}'s dreams and {username}'s ability to achieve them.",
            f"Success is not final, failure is not fatal: it is the courage to continue that counts, {username}.",
            f"Believe in {username}'s potential and {username} will go far.",
            f"Every great story begins with a hero, and {username} is the hero of {username}'s story.",
            f"The greatest glory in living lies not in never falling, but in rising every time we fall, {username}.",
            f"Believe in {username} and {username} will be unstoppable.",
            f"If {username} can dream it, {username} can achieve it.",
            f"Don't let yesterday take up too much of today, {username}.",
            f"{username}, all the great performers I have worked with are fueled by a personal dream."
            f"{username}, time stays long enough for anyone who will use it."
            f"{username}, setting an example is not the main means of influencing another, it is the only means."
        ]

        return random.choice(messages)